name: PHP-Test

on:
  push:
  pull_request:

jobs:
  Static-Analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      uses: php-actions/composer@v6
      with:
        command: validate
        php_version: 8.0

    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        command: install --prefer-dist
        php_version: 8.0

    - name: PHPStan Static Analysis
      uses: php-actions/phpstan@v2
      with:
        command: analyse
        configuration: phpstan.neon
        memory_limit: 256M
        php_version: 8.0

    - name: PHPUnit Tests
      uses: php-actions/phpunit@v3
      with:
        php_extensions: xdebug
        configuration: phpunit.xml
      env:
        XDEBUG_MODE: coverage

    - name: Code Coverage
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage/clover.xml
